CREATE USER junit_user;
GRANT CONNECT, RESOURCE, CREATE SESSION, DBA, DV_REALM_RESOURCE TO junit_user CONTAINER=ALL;
ALTER USER  junit_user IDENTIFIED BY "junit_user";
ALTER USER junit_user QUOTA UNLIMITED ON USERS;
commit;
exit;